# Site Descriptions
title: Ahmed Kleit
email: kleit.ahmed@gmail.com
description: Ahmed Kleit Portfolio
baseurl: ""
url: ""

# Build Settings
markdown: kramdown
collections:
  projects:
    title: Projects
    output: true
  pages:
    title: Pages
    output: true
  uploads:
    title: Uploads
    output: true
sass:
  sass_dir: /assets/css
  style: compressed
gems:
  - jekyll-autoprefixer
exclude:
  - Gemfile
  - Gemfile.lock
