---
title: Ahmed Kleit
timezone: UTC
collections:
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
email: kleit.ahmed@gmail.com
description: Ahmed Kleit Portfolio
baseurl: ''
url: ''
markdown: kramdown
sass:
  sass_dir: "/assets/css"
  style: compressed
gems:
- jekyll-autoprefixer
exclude:
- Gemfile
- Gemfile.lock
